# setup_claude_auth.ps1
# Extracts Claude OAuth tokens from the local Claude Code credentials file
# and writes them into tradecore/.env so Docker can use them.
#
# Usage (local → server):
#   1. Run this script locally to update .env
#   2. scp/rsync .env to your server
#   3. docker compose up -d

param(
    [string]$EnvFile = "$PSScriptRoot\..\tradecore\.env"
)

$CredsFile = "$env:USERPROFILE\.claude\.credentials.json"

if (-not (Test-Path $CredsFile)) {
    Write-Error "Credentials file not found at $CredsFile. Run 'claude login' first."
    exit 1
}

$creds = Get-Content $CredsFile -Raw | ConvertFrom-Json
$oauth  = $creds.claudeAiOauth

if (-not $oauth -or -not $oauth.accessToken) {
    Write-Error "claudeAiOauth.accessToken not found in credentials file."
    exit 1
}

$accessToken  = $oauth.accessToken
$refreshToken = $oauth.refreshToken
$expiresAt    = $oauth.expiresAt

Write-Host "Read tokens from $CredsFile"
Write-Host "  Access token : $($accessToken.Substring(0, 20))..."
Write-Host "  Expires at   : $(([DateTimeOffset]::FromUnixTimeMilliseconds($expiresAt)).LocalDateTime)"

# Read existing .env, strip old CLAUDE_ lines, append fresh ones
$envPath = (Resolve-Path $EnvFile -ErrorAction SilentlyContinue)?.Path
if (-not $envPath) {
    Write-Error ".env not found at $EnvFile. Run this from the repo root or pass -EnvFile <path>."
    exit 1
}

$lines = Get-Content $envPath | Where-Object { $_ -notmatch '^CLAUDE_(ACCESS|REFRESH)_TOKEN=' -and $_ -notmatch '^CLAUDE_TOKEN_EXPIRES_AT=' }

$lines += ""
$lines += "# Claude OAuth — generated by setup_claude_auth.ps1"
$lines += "CLAUDE_ACCESS_TOKEN=$accessToken"
$lines += "CLAUDE_REFRESH_TOKEN=$refreshToken"
$lines += "CLAUDE_TOKEN_EXPIRES_AT=$expiresAt"

$lines | Set-Content $envPath -Encoding utf8
Write-Host ""
Write-Host "Updated $envPath" -ForegroundColor Green
Write-Host "Next: scp $envPath user@your-server:/path/to/tradecore/.env"
